import Head from 'next/head';
import AppProvider from 'utils/context';
import PropTypes from 'prop-types';
import 'styles/globals.css';

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>Frontend Challenge</title>
				<meta name="description" content="Generated by Lila Software Studio" />
				<link rel="icon" href="favicon.ico" />
			</Head>
			<AppProvider>
				<Component {...pageProps} />
			</AppProvider>
		</>
	);
}

export default MyApp;

MyApp.propTypes = {
	Component: PropTypes.elementType,
	pageProps: PropTypes.object,
};
